#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/infinix/X6812B

PRODUCT_COPY_FILES += \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/020b0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020b0000000000000000000000000000.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/020b0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020b0000000000000000000000000000.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/030b0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030b0000000000000000000000000000.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/030b0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030b0000000000000000000000000000.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/09010000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09010000000000000000000000000000.tabin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/09190000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09190000000000000000000000000000.tabin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/511ead0a000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/511ead0a000000000000000000000000.tabin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin \
    vendor/infinix/X6812B/proprietary/vendor/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/M_Segment_DoubleLoss_V1.model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/M_Segment_DoubleLoss_V1.model \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/Transsion_Segment_Pre.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/Transsion_Segment_Pre.mnn \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/eyes_detect_model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/eyes_detect_model \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/facerecheck.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facerecheck.bin \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/facerecheck.param:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facerecheck.param \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/lightforgender_addindian_tf113_test5.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgender_addindian_tf113_test5.tflite \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/lightforgender_addindian_tf113_test5_converted.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgender_addindian_tf113_test5_converted.mnn \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/lightforgenderandage_tf113_test4.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgenderandage_tf113_test4.tflite \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/lightforgenderandage_tf113_test4_converted.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgenderandage_tf113_test4_converted.mnn \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/megii_dualcam/cache_data:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/cache_data \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/megii_dualcam/capture_cache:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/capture_cache \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/megii_dualcam/capture_model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/capture_model \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/megii_dualcam/capture_policy:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/capture_policy \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/megii_dualcam/dof_mecp.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/dof_mecp.bin \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/megii_dualcam/for_mt6768_mt6785:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/for_mt6768_mt6785 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/megii_dualcam/preview_cache:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/preview_cache \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/megii_dualcam/preview_model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/preview_model \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/portrait_repair_composite_hardcode_lite_3.4.20.model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/portrait_repair_composite_hardcode_lite_3.4.20.model \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/scene.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/scene.tflite \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/segment.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/segment.tflite \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/segmentPre.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/segmentPre.tflite \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/model/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sr_params.xml \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/tran_fd/detector/rf_newsshratio4_newresult_opt.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/tran_fd/detector/rf_newsshratio4_newresult_opt.bin \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/tran_fd/detector/rf_newsshratio4_newresult_opt.param:$(TARGET_COPY_OUT_VENDOR)/data/camera/tran_fd/detector/rf_newsshratio4_newresult_opt.param \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/tran_fd/tracker/det2.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/tran_fd/tracker/det2.bin \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/tran_fd/tracker/det2.param:$(TARGET_COPY_OUT_VENDOR)/data/camera/tran_fd/tracker/det2.param \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_1280x720.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1280x720.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_1280x720.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1280x720.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_1920x1080.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1920x1080.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_1920x1080.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1920x1080.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_2432x2432.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2432x2432.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_2432x2432.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2432x2432.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_2560x1440.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2560x1440.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_2560x1440.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2560x1440.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_2624x1152.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2624x1152.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_2624x1152.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2624x1152.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_2944x2944.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2944x2944.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_2944x2944.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2944x2944.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_3264x2448.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3264x2448.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_3264x2448.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3264x2448.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_3840x2160.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3840x2160.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_3840x2160.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3840x2160.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_3936x1728.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3936x1728.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_3936x1728.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3936x1728.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_3968x2976.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3968x2976.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_3968x2976.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3968x2976.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_4080x3060.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_4080x3060.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_4080x3060.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_4080x3060.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_5952x5952.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_5952x5952.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_5952x5952.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_5952x5952.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_640x480.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_640x480.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_640x480.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_640x480.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_7872x3456.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_7872x3456.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_7872x3456.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_7872x3456.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_8160x6120.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_8160x6120.nv21 \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_8160x6120.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_8160x6120.yuyv \
    vendor/infinix/X6812B/proprietary/vendor/data/camera/watermark/watermark_config:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_config \
    vendor/infinix/X6812B/proprietary/vendor/etc/.tp/.ht120.mtc:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.ht120.mtc \
    vendor/infinix/X6812B/proprietary/vendor/etc/.tp/.thermal_policy_00:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_00 \
    vendor/infinix/X6812B/proprietary/vendor/etc/.tp/.thermal_policy_03:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_03 \
    vendor/infinix/X6812B/proprietary/vendor/etc/.tp/.thermal_policy_05:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_05 \
    vendor/infinix/X6812B/proprietary/vendor/etc/.tp/.thermal_policy_08:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_08 \
    vendor/infinix/X6812B/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/infinix/X6812B/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/infinix/X6812B/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/AudioParamOptions.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/BtInfo_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/BtInfo_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/HpImpedance_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/HpImpedance_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/MicInfo_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/MicInfo_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackACF_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackACF_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackDRC_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackDRC_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackHCF_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackHCF_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackVolAna_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackVolDigi_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Playback_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Playback_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Playback_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordDMNR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordFIR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordFIR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordVol_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RecordVol_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Record_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Record_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Record_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RingbackVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RingbackVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RingbackVol_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/RingbackVol_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SoundEnhancement_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SoundEnhancement_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechDMNR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechEchoRef_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechGeneral_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechGeneral_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechMagiClarity_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechNetwork_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechNetwork_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechVol_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/SpeechVol_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Speech_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Speech_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Speech_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/USBCall_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/USBCall_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/USBDevice_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/USBDevice_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/UplinkConfiguration_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPDMNR_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPDMNR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPGeneral_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPGeneral_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPVolUI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPVolUI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPVol_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPVol_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIP_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIP_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIP_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPv2General_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPv2General_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPv2UI_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPv2UI_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPv2_ParamTreeView.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoIPv2_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoWDspAec_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoWDspAec_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoWHwVad_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VoWHwVad_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VolumeGainMapUL_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VolumeGainMap_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/VolumeGainMap_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Volume_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/audio_param_ce/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_ce/Volume_ParamUnitDesc.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/aurisys_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_param/Speech_AudioParam.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/camera/model/bokeh_model/cache_data:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/bokeh_model/cache_data \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/factory.ini:$(TARGET_COPY_OUT_VENDOR)/etc/factory.ini \
    vendor/infinix/X6812B/proprietary/vendor/etc/fstb.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/fstb.cfg \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-mediatek.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-mediatek.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service.trustonic.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.media.omx@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.omx@1.0-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.sensors@2.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@2.0-service-mediatek.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.thermal@2.0-service.mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@2.0-service.mtk.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/android.hardware.wifi@1.0-service-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi@1.0-service-lazy.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/atcid.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/atcid.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/audiocmdservice_atci.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/audiocmdservice_atci.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/bootperf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/bootperf.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/em_hidl_user.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/em_hidl_user.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.bip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.cccifsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccifsd.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.md_apps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md_apps.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.udc_lib.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.udc_lib.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.wfca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wfca.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/init_connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_connectivity.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/md_monitor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/md_monitor.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/networksetting.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/networksetting.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/trustonic_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic_kmsetkey_ca.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.mediatek.hardware.dfps@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.dfps@1.0-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.mediatek.hardware.gpu@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.gpu@1.0-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.5-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.5-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkcodecservice@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkcodecservice@1.1-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.silead.hardware.fingerprintext@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.silead.hardware.fingerprintext@1.0-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.conf \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootCA.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootCA.crt \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG2.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG2.crt \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG3.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG3.crt \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root-R3.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Root-R3.cer \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/gold.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/gold.cer \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/thawte.der \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/ssl/openssl.cnf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ssl/openssl.cnf \
    vendor/infinix/X6812B/proprietary/vendor/etc/ipsec/strongswan.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/strongswan.conf \
    vendor/infinix/X6812B/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/infinix/X6812B/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/infinix/X6812B/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/infinix/X6812B/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/spn-conf-op09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/spn-conf-op09.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/infinix/X6812B/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/infinix/X6812B/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/infinix/X6812B/proprietary/vendor/firmware/WIFI_RAM_CODE_soc1_0_1a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc1_0_1a_1.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/infinix/X6812B/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt1151_default_firmware2.img:$(TARGET_COPY_OUT_VENDOR)/firmware/gt1151_default_firmware2.img \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_6785v96.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6785v96.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_6785v99.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6785v99.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6853v01.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6873v01.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_6885v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v01.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_6885v1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v1.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_6885v9c.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v9c.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6893v01.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_90hz6885.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_90hz6885.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_cfg_gt9885v1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_gt9885v1.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6785a4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6785a4.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6785ae.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6785ae.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6853v01.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6873v01.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6885a1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885a1.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6885af.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885af.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6885b0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885b0.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6885b1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885b1.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6885v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885v01.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/gt9886_firmware_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6893v01.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc1_0_patch_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_patch_mcu_1a_1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc1_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_1a_1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc1_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_mcu_1a_1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc1_0_ram_wifi_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_wifi_1a_1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc3_0_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_bt_1_1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc3_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_bt_1a_1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc3_0_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_1_1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc3_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_1a_1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/soc3_0_ram_mcu_e1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_e1_hdr.bin \
    vendor/infinix/X6812B/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/infinix/X6812B/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg

PRODUCT_PACKAGES += \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    libGLES_meow \
    libMEOW_gift \
    libMEOW_trace \
    gc02m1b_mipi_raw_tuning \
    gc08a3_mipi_raw_tuning \
    gc6153_serial_yuv_tuning \
    gc8034_mipi_raw_tuning \
    android.hardware.bluetooth@1.0-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    android.hardware.thermal@2.0-impl \
    audio.primary.mt6768 \
    audio.r_submix.mt6768 \
    audio.usb.mt6768 \
    dfps.mt6768 \
    fingerprint.silead.default \
    gps.default \
    libMcGatekeeper \
    libSoftGatekeeper \
    thermal.mt6768 \
    vendor.mediatek.hardware.bluetooth.audio@2.1-impl \
    vendor.mediatek.hardware.dfps@1.0-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.5-impl \
    vendor.mediatek.hardware.mtkcodecservice@1.1-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.pq@2.6-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libMcClient \
    libMtkOmxCore \
    libMtkSpeechEnh \
    libNoFpsActor \
    libOpenCL \
    libTEECommon \
    lib_iir \
    lib_speech_enh \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libaedv \
    libalsautils-v30 \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_audio_session_mediatek \
    libbluetooth_hw_test \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbluetooth_relayer \
    libbluetoothem_mtk \
    libbt-vendor \
    libbwc \
    libcam.halsensor.hwintegration \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcrypto-mdapp \
    libcurl-md \
    libcurl_xcap_md \
    libcustom_nvram \
    libcvsd_mtk \
    libdpframework \
    libfile_op \
    libfpspolicy \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_uree \
    libhevce_sb.ca7.android \
    libhwm \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libladder \
    libminiui \
    libmnetlink_v104 \
    libmsbc_mtk \
    libmtcloader \
    libmtk_drvb \
    libmtkares \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtklimiter_vendor \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtkshifter_vendor \
    libmtksysutils \
    libnvram \
    libnvram_daemon_callback \
    libnvram_platform \
    libnvram_sec \
    libpixelflinger \
    libpowerhalwrap_vendor \
    libpq_cust_base \
    libpq_prot \
    libsl_fp_impl \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libssl-mdapp \
    libstagefrighthw \
    libsysenv \
    libthha \
    libtranlog \
    libudf \
    libutinterface_custom_md \
    libutinterface_md \
    libvcodec_oal \
    libverno \
    libwo \
    libwpa_client \
    libwvhidl \
    libwvdrmengine \
    ov02b1b_mipi_raw_tuning \
    pblcgc02m1b_mipi_raw_tuning \
    pblcgc08a3_mipi_raw_tuning \
    pblcgc6153_serial_yuv_tuning \
    pblcgc8034_mipi_raw_tuning \
    pblcov02b1b_mipi_raw_tuning \
    pblcs5kjn1_mipi_raw_tuning \
    pblcs5kjn1ext2_mipi_raw_tuning \
    s5kjn1_mipi_raw_tuning \
    s5kjn1ext2_mipi_raw_tuning \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.dfps@1.0 \
    vendor.mediatek.hardware.gpu@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.mdmonitor@1.0 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mtkcodecservice@1.1 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    vendor.silead.hardware.fingerprintext@1.0-adapter-helper \
    vendor.silead.hardware.fingerprintext@1.0 \
    vendor.transsion.hardware.trancam.trancamserver@1.0 \
    kmsetkey.default \
    kmsetkey.trustonic \
    libDR \
    libHEVCdec_sa.ca7.android \
    libMtkOmxAdpcmDec \
    libMtkOmxAlacDec \
    libMtkOmxApeDec \
    libMtkOmxGsmDec \
    libMtkOmxMp3Dec \
    libMtkOmxVdecEx \
    libMtkOmxVenc \
    libfgauge_gm30 \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmnl \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    libstorage_otp \
    libthermalalgo \
    libvc1dec_sa.ca7 \
    libvcodec_utility \
    libvcodecdrv \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpud_vcodec \
    libvt_custom \
    gc02m1b_mipi_raw_IdxMgr \
    gc08a3_mipi_raw_IdxMgr \
    gc6153_serial_yuv_IdxMgr \
    gc8034_mipi_raw_IdxMgr \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    fingerprint.mt6768 \
    gatekeeper.default \
    gatekeeper.mt6768 \
    gatekeeper.x6812_h6912 \
    hwcomposer.mt6768 \
    sensors.mt6768 \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    lbs_hidl_service-impl \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.core \
    lib3a.af \
    lib3a.awb.core \
    lib3a.awb \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.flash \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    libImageEval \
    libMtkSImage \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTranASD \
    libTranArcDro \
    libTranArcFilter \
    libTranArcHDR \
    libTranArcLowLight \
    libTranArcNightHawk \
    libTranArcPicselfie \
    libTranDenoise \
    libTranExtImgProc \
    libTranEyeDetect \
    libTranFaceBeauty \
    libTranFaceDetect \
    libTranFaceDetectCoordinate \
    libTranHumanLight \
    libTranMegDualRefocus \
    libTranPlatHW \
    libTranSTPRRepair \
    libTranSTSingleBlur \
    libTranSlimBody \
    libTranStSuperResolution \
    libTranUndistort \
    libTran_Log \
    libTran_mtkPowerAPI \
    libWaterMarkProc \
    lib_bsscore \
    lib_sr_indep_ocl \
    libabfadp \
    libacdk \
    libamipengine \
    libanc_dc_base \
    libarcsoft_beautyshot \
    libarcsoft_dro \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_shot \
    libarcsoft_night_hawk \
    libarcsoft_picselfie_algorithm \
    libc++_shared \
    libcalculatesharpness \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.lsctbl \
    libcam.hal3a.v3.nvram \
    libcam.hal3a.v3 \
    libcam.halisp \
    libcam.halsensor \
    libcam.iopipe \
    libcam.lcs \
    libcam.pdtblgen \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam3_tranpriorityctrl \
    libcam3_transerverengine \
    libcamalgo.3dnr \
    libcamalgo.abf \
    libcamalgo.asd \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.flicker \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.nr \
    libcamalgo.utility \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcameracustom.eis \
    libcameracustom.plugin \
    libcameracustom \
    libcharon-ss \
    libdenoise \
    libeffecthal.base \
    libeyedetector \
    libfacedetector \
    libfacesattribute \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libfft_vendor \
    libforkexecwrap \
    libhydra \
    libifcutils_mtk \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libkeystore-engine-wifi-hidl \
    libkeystore-wifi-hidl \
    libkmsetkey \
    libksensor \
    liblpcnr \
    libmfllcore \
    libmpbase \
    libmsnr \
    libmtk-ril \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkisp_metadata \
    libmtkrilutils \
    libmtktinyxml \
    libmtkutils \
    libportrait_repair_ocl \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librilfusion \
    librmsclib1 \
    libsdk_sr \
    libsegmention \
    libsegmentionPre \
    libsensor_custom \
    libsimaka \
    libst_mobile \
    libst_sr_models \
    libstblur_capture_api \
    libstereoinfoaccessor_vsdof \
    libstrongswan \
    libtf_asd_lib \
    libtflite_native_gainference \
    libtflite_native_inference \
    libtflite_native_seginference \
    libtranssion_beauty \
    libtranssion_bodybeauty \
    libtranssion_cal \
    libundistort_64 \
    libwa_dof \
    libwa_rtdof \
    libwifi-hal-mtk \
    libwifitest \
    libmtkcam_streaminfo_plugin-p1stt \
    ov02b1b_mipi_raw_IdxMgr \
    pblcgc02m1b_mipi_raw_IdxMgr \
    pblcgc08a3_mipi_raw_IdxMgr \
    pblcgc6153_serial_yuv_IdxMgr \
    pblcgc8034_mipi_raw_IdxMgr \
    pblcov02b1b_mipi_raw_IdxMgr \
    pblcs5kjn1_mipi_raw_IdxMgr \
    pblcs5kjn1ext2_mipi_raw_IdxMgr \
    s5kjn1_mipi_raw_IdxMgr \
    s5kjn1ext2_mipi_raw_IdxMgr \
    vendor.mediatek.hardware.atci@1.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.engineermode@1.0 \
    vendor.mediatek.hardware.engineermode@1.1 \
    vendor.mediatek.hardware.engineermode@1.2 \
    vendor.mediatek.hardware.engineermode@1.3 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@2.1 \
    vendor.mediatek.hardware.mtkradioex@2.2 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.wifi.supplicant@2.0 \
    vendor.mediatek.hardware.wifi.supplicant@2.1 \
    vendor.mediatek.hardware.wifi.supplicant@2.2 \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-ims-extension-plugin \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    android.hardware.biometrics.fingerprint@2.1-service.xml \
    android.hardware.wifi@1.0-service.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vendor.mediatek.hardware.gpu@1.0-service.xml \
    atcid \
    audiocmdservice_atci \
    autobt \
    bip \
    ccci_fsd \
    ccci_mdinit \
    ccci_rpcd \
    charon \
    epdg_wod \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.bluetooth@1.0-service-mediatek \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gnss@2.1-service-mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.0-service.trustonic \
    android.hardware.media.omx@1.0-service \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.sensors@2.0-service-mediatek \
    android.hardware.thermal@2.0-service.mtk \
    android.hardware.wifi@1.0-service-lazy \
    camerahalserver \
    mtkfusionrild \
    vendor.mediatek.hardware.dfps@1.0-service \
    vendor.mediatek.hardware.gpu@1.0-service \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mms@1.5-service \
    vendor.mediatek.hardware.mtkcodecservice@1.1-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    ipsec_mon \
    lbs_hidl_service \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    libccu_gc02m1b_mipi_raw.dm \
    libccu_gc02m1b_mipi_raw.pm \
    libccu_gc08a3_mipi_raw.dm \
    libccu_gc08a3_mipi_raw.pm \
    libccu_gc8034_mipi_raw.dm \
    libccu_gc8034_mipi_raw.pm \
    libccu_ov02b1b_mipi_raw.dm \
    libccu_ov02b1b_mipi_raw.pm \
    libccu_s5kjn1_mipi_raw.dm \
    libccu_s5kjn1_mipi_raw.pm \
    libccu_s5kjn1ext2_mipi_raw.dm \
    libccu_s5kjn1ext2_mipi_raw.pm \
    md_monitor \
    md_monitor_ctrl \
    mnld \
    mtk_agpsd \
    muxreport \
    netdagent \
    netdc \
    nvram_daemon \
    starter \
    stroke \
    thermal \
    thermal_manager \
    thermalloadalgod \
    trustonic_kmsetkey_ca \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_stack \
    volte_ua \
    vpud \
    wfca \
    wlan_assistant \
    wmt_launcher \
    wmt_loader
